title: Digital Project Managment
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/ect123/intro-digital-project-management/\">View workshop content in GitHub</a>"
